# Generated by Django 2.1.15 on 2020-06-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblogmodel',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
