# Generated by Django 2.1.15 on 2020-06-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog_app', '0002_auto_20200626_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblogmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
