# Generated by Django 2.1.15 on 2020-06-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_project',
            name='img',
            field=models.ImageField(upload_to='Media'),
        ),
    ]
